#!/usr/bin/env bash
# Build cross-platform tsctl binaries via `bun build --compile`, publish a
# GitHub release, and push an updated Homebrew formula to
# akshitkrnagpal/homebrew-tap.
#
# Requires:
#   - bun
#   - gh (authenticated; `gh auth status` to verify)
#   - shasum (default on macOS)
#   - jq
#
# Usage:
#   scripts/release.sh                  # uses version from package.json
#   scripts/release.sh 0.4.0             # override version
#
# The script is idempotent up to the GH release step: if a tag/release
# already exists, gh will refuse and you can re-run after `gh release
# delete vX.Y.Z`.

set -euo pipefail

REPO_OWNER="akshitkrnagpal"
REPO_NAME="tsctl"
TAP_OWNER="akshitkrnagpal"
TAP_NAME="homebrew-tap"
ENTRY="src/cli/index.ts"
BIN_NAME="tsctl"

# --- version --------------------------------------------------------------

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  VERSION=$(jq -r .version package.json)
fi
if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
  echo "could not determine version" >&2
  exit 1
fi
TAG="v$VERSION"

echo "==> Releasing ${REPO_OWNER}/${REPO_NAME}@${TAG}"

# --- preconditions --------------------------------------------------------

if ! command -v bun >/dev/null; then
  echo "bun not found on PATH" >&2; exit 1
fi
if ! command -v gh >/dev/null; then
  echo "gh not found on PATH" >&2; exit 1
fi
if ! command -v jq >/dev/null; then
  echo "jq not found on PATH" >&2; exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "gh CLI is not authenticated; run \`gh auth login\`" >&2; exit 1
fi

if ! git diff --quiet HEAD; then
  echo "working tree is dirty; commit/stash before releasing" >&2; exit 1
fi

# --- build matrix ---------------------------------------------------------

DIST=dist/release
rm -rf "$DIST"
mkdir -p "$DIST"

# Build sequentially. SHAs collected into parallel `SHA_<name>` shell
# variables (avoids bash 3.2 lacking associative arrays - macOS default).
TARGETS=(
  "darwin-arm64:bun-darwin-arm64"
  "darwin-x64:bun-darwin-x64"
  "linux-arm64:bun-linux-arm64"
  "linux-x64:bun-linux-x64"
)

SHA_DARWIN_ARM64=""
SHA_DARWIN_X64=""
SHA_LINUX_ARM64=""
SHA_LINUX_X64=""

for entry in "${TARGETS[@]}"; do
  name="${entry%%:*}"
  target="${entry##*:}"
  out_dir="$DIST/${BIN_NAME}_${VERSION}_${name}"
  mkdir -p "$out_dir"
  out_bin="$out_dir/$BIN_NAME"

  echo "==> Building $name ($target)"
  bun build "$ENTRY" --compile --target="$target" --outfile "$out_bin" --minify >/dev/null
  chmod +x "$out_bin"

  cp README.md "$out_dir/" 2>/dev/null || true
  cp LICENSE "$out_dir/" 2>/dev/null || true

  archive="$DIST/${BIN_NAME}_${VERSION}_${name}.tar.gz"
  tar -C "$DIST" -czf "$archive" "$(basename "$out_dir")"
  rm -rf "$out_dir"

  sha=$(shasum -a 256 "$archive" | awk '{print $1}')
  case "$name" in
    darwin-arm64) SHA_DARWIN_ARM64="$sha" ;;
    darwin-x64)   SHA_DARWIN_X64="$sha" ;;
    linux-arm64)  SHA_LINUX_ARM64="$sha" ;;
    linux-x64)    SHA_LINUX_X64="$sha" ;;
  esac
  echo "    archive: $(basename "$archive")"
  echo "    sha256:  $sha"
done

# --- write checksums file -------------------------------------------------

CHECKSUMS="$DIST/checksums.txt"
( cd "$DIST" && shasum -a 256 *.tar.gz > "$(basename "$CHECKSUMS")" )

# --- tag + GH release -----------------------------------------------------

if ! git rev-parse "$TAG" >/dev/null 2>&1; then
  echo "==> Tagging $TAG"
  git tag -a "$TAG" -m "Release $TAG"
  git push origin "$TAG"
fi

if gh release view "$TAG" --repo "$REPO_OWNER/$REPO_NAME" >/dev/null 2>&1; then
  echo "==> GH release $TAG already exists, uploading assets"
  gh release upload "$TAG" "$DIST"/*.tar.gz "$CHECKSUMS" \
    --repo "$REPO_OWNER/$REPO_NAME" --clobber
else
  echo "==> Creating GH release $TAG"
  gh release create "$TAG" "$DIST"/*.tar.gz "$CHECKSUMS" \
    --repo "$REPO_OWNER/$REPO_NAME" \
    --title "$TAG" \
    --notes "Release $TAG. See [CHANGELOG](https://github.com/$REPO_OWNER/$REPO_NAME/blob/main/CHANGELOG.md) if available."
fi

# --- generate Homebrew formula --------------------------------------------

FORMULA_TMP=$(mktemp)
cat > "$FORMULA_TMP" <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by scripts/release.sh in akshitkrnagpal/tsctl.
# DO NOT EDIT BY HAND - your changes will be overwritten on next release.
class Tsctl < Formula
  desc "Terraform-like CLI for managing Typesense"
  homepage "https://github.com/${REPO_OWNER}/${REPO_NAME}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/${TAG}/${BIN_NAME}_${VERSION}_darwin-x64.tar.gz"
      sha256 "${SHA_DARWIN_X64}"
    elsif Hardware::CPU.arm?
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/${TAG}/${BIN_NAME}_${VERSION}_darwin-arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/${TAG}/${BIN_NAME}_${VERSION}_linux-x64.tar.gz"
      sha256 "${SHA_LINUX_X64}"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/${TAG}/${BIN_NAME}_${VERSION}_linux-arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
  end

  def install
    bin.install "${BIN_NAME}"
  end

  test do
    system "#{bin}/${BIN_NAME}", "--version"
  end
end
EOF

# --- push formula to tap --------------------------------------------------

TAP_DIR=$(mktemp -d)
trap 'rm -rf "$TAP_DIR" "$FORMULA_TMP"' EXIT

echo "==> Updating ${TAP_OWNER}/${TAP_NAME}/Formula/${BIN_NAME}.rb"
gh repo clone "${TAP_OWNER}/${TAP_NAME}" "$TAP_DIR" -- --quiet
mkdir -p "$TAP_DIR/Formula"
cp "$FORMULA_TMP" "$TAP_DIR/Formula/${BIN_NAME}.rb"

(
  cd "$TAP_DIR"
  if git diff --quiet; then
    echo "    formula unchanged, nothing to commit"
  else
    git add "Formula/${BIN_NAME}.rb"
    git commit -m "${BIN_NAME}: ${VERSION}"
    git push origin HEAD
    echo "    pushed"
  fi
)

echo ""
echo "==> Done."
echo "    Release: https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/tag/${TAG}"
echo "    Formula: https://github.com/${TAP_OWNER}/${TAP_NAME}/blob/HEAD/Formula/${BIN_NAME}.rb"
echo ""
echo "    Install: brew install ${TAP_OWNER}/tap/${BIN_NAME}"
