// Main entry point for library usage
// Users can import { defineConfig } from "tsctl"

export {
  defineConfig,
  // Types
  type TypesenseConfig,
  type CollectionConfig,
  type AliasConfig,
  type SynonymConfig,
  type SynonymSetConfig,
  type SynonymSetItem,
  type OverrideConfig,
  type CurationSetConfig,
  type CurationItem,
  type StopwordSetConfig,
  type PresetConfig,
  type StemmingDictionaryConfig,
  type StemmingWord,
  type AnalyticsRuleConfig,
  type ApiKeyConfig,
  type Field,
  type FieldType,
  type ConnectionConfig,
  // Schemas (for validation)
  TypesenseConfigSchema,
  CollectionConfigSchema,
  AliasConfigSchema,
  SynonymConfigSchema,
  SynonymSetConfigSchema,
  SynonymSetItemSchema,
  OverrideConfigSchema,
  CurationSetConfigSchema,
  CurationItemSchema,
  CurationRuleSchema,
  StopwordSetConfigSchema,
  PresetConfigSchema,
  StemmingDictionaryConfigSchema,
  StemmingWordSchema,
  AnalyticsRuleConfigSchema,
  ApiKeyConfigSchema,
  FieldSchema,
  FieldTypeSchema,
  ConnectionConfigSchema,
} from "./types/index.js";
